package com.example.back.common;

import java.util.ArrayList;
import java.util.List;

public class scheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public scheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatusnameIsNull() {
            addCriterion("statusname is null");
            return (Criteria) this;
        }

        public Criteria andStatusnameIsNotNull() {
            addCriterion("statusname is not null");
            return (Criteria) this;
        }

        public Criteria andStatusnameEqualTo(String value) {
            addCriterion("statusname =", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameNotEqualTo(String value) {
            addCriterion("statusname <>", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameGreaterThan(String value) {
            addCriterion("statusname >", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameGreaterThanOrEqualTo(String value) {
            addCriterion("statusname >=", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameLessThan(String value) {
            addCriterion("statusname <", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameLessThanOrEqualTo(String value) {
            addCriterion("statusname <=", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameLike(String value) {
            addCriterion("statusname like", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameNotLike(String value) {
            addCriterion("statusname not like", value, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameIn(List<String> values) {
            addCriterion("statusname in", values, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameNotIn(List<String> values) {
            addCriterion("statusname not in", values, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameBetween(String value1, String value2) {
            addCriterion("statusname between", value1, value2, "statusname");
            return (Criteria) this;
        }

        public Criteria andStatusnameNotBetween(String value1, String value2) {
            addCriterion("statusname not between", value1, value2, "statusname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameIsNull() {
            addCriterion("subitemname is null");
            return (Criteria) this;
        }

        public Criteria andSubitemnameIsNotNull() {
            addCriterion("subitemname is not null");
            return (Criteria) this;
        }

        public Criteria andSubitemnameEqualTo(String value) {
            addCriterion("subitemname =", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameNotEqualTo(String value) {
            addCriterion("subitemname <>", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameGreaterThan(String value) {
            addCriterion("subitemname >", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameGreaterThanOrEqualTo(String value) {
            addCriterion("subitemname >=", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameLessThan(String value) {
            addCriterion("subitemname <", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameLessThanOrEqualTo(String value) {
            addCriterion("subitemname <=", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameLike(String value) {
            addCriterion("subitemname like", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameNotLike(String value) {
            addCriterion("subitemname not like", value, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameIn(List<String> values) {
            addCriterion("subitemname in", values, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameNotIn(List<String> values) {
            addCriterion("subitemname not in", values, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameBetween(String value1, String value2) {
            addCriterion("subitemname between", value1, value2, "subitemname");
            return (Criteria) this;
        }

        public Criteria andSubitemnameNotBetween(String value1, String value2) {
            addCriterion("subitemname not between", value1, value2, "subitemname");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andStartdatecnIsNull() {
            addCriterion("startdatecn is null");
            return (Criteria) this;
        }

        public Criteria andStartdatecnIsNotNull() {
            addCriterion("startdatecn is not null");
            return (Criteria) this;
        }

        public Criteria andStartdatecnEqualTo(String value) {
            addCriterion("startdatecn =", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnNotEqualTo(String value) {
            addCriterion("startdatecn <>", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnGreaterThan(String value) {
            addCriterion("startdatecn >", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnGreaterThanOrEqualTo(String value) {
            addCriterion("startdatecn >=", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnLessThan(String value) {
            addCriterion("startdatecn <", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnLessThanOrEqualTo(String value) {
            addCriterion("startdatecn <=", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnLike(String value) {
            addCriterion("startdatecn like", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnNotLike(String value) {
            addCriterion("startdatecn not like", value, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnIn(List<String> values) {
            addCriterion("startdatecn in", values, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnNotIn(List<String> values) {
            addCriterion("startdatecn not in", values, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnBetween(String value1, String value2) {
            addCriterion("startdatecn between", value1, value2, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andStartdatecnNotBetween(String value1, String value2) {
            addCriterion("startdatecn not between", value1, value2, "startdatecn");
            return (Criteria) this;
        }

        public Criteria andVenuenameIsNull() {
            addCriterion("venuename is null");
            return (Criteria) this;
        }

        public Criteria andVenuenameIsNotNull() {
            addCriterion("venuename is not null");
            return (Criteria) this;
        }

        public Criteria andVenuenameEqualTo(String value) {
            addCriterion("venuename =", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameNotEqualTo(String value) {
            addCriterion("venuename <>", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameGreaterThan(String value) {
            addCriterion("venuename >", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameGreaterThanOrEqualTo(String value) {
            addCriterion("venuename >=", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameLessThan(String value) {
            addCriterion("venuename <", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameLessThanOrEqualTo(String value) {
            addCriterion("venuename <=", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameLike(String value) {
            addCriterion("venuename like", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameNotLike(String value) {
            addCriterion("venuename not like", value, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameIn(List<String> values) {
            addCriterion("venuename in", values, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameNotIn(List<String> values) {
            addCriterion("venuename not in", values, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameBetween(String value1, String value2) {
            addCriterion("venuename between", value1, value2, "venuename");
            return (Criteria) this;
        }

        public Criteria andVenuenameNotBetween(String value1, String value2) {
            addCriterion("venuename not between", value1, value2, "venuename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 24 16:19:06 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}