package com.example.back.common;

import java.io.Serializable;

public class Schedule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.statusname
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    private String statusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.subitemname
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    private String subitemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.title
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.startdatecn
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    private String startdatecn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.venuename
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    private String venuename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.statusname
     *
     * @return the value of schedule.statusname
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public String getStatusname() {
        return statusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.statusname
     *
     * @param statusname the value for schedule.statusname
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public void setStatusname(String statusname) {
        this.statusname = statusname == null ? null : statusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.subitemname
     *
     * @return the value of schedule.subitemname
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public String getSubitemname() {
        return subitemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.subitemname
     *
     * @param subitemname the value for schedule.subitemname
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public void setSubitemname(String subitemname) {
        this.subitemname = subitemname == null ? null : subitemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.title
     *
     * @return the value of schedule.title
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.title
     *
     * @param title the value for schedule.title
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.startdatecn
     *
     * @return the value of schedule.startdatecn
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public String getStartdatecn() {
        return startdatecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.startdatecn
     *
     * @param startdatecn the value for schedule.startdatecn
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public void setStartdatecn(String startdatecn) {
        this.startdatecn = startdatecn == null ? null : startdatecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.venuename
     *
     * @return the value of schedule.venuename
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public String getVenuename() {
        return venuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.venuename
     *
     * @param venuename the value for schedule.venuename
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    public void setVenuename(String venuename) {
        this.venuename = venuename == null ? null : venuename.trim();
    }
}