package com.example.back.common;

public class schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.homeid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String homeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.h5pageid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String h5pageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.statusname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String statusname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.itemcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String itemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.subitemname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String subitemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.vrtotalurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String vrtotalurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.enddatecn
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String enddatecn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.albumurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String albumurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.title
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.vrlivecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String vrlivecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.deletedflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String deletedflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.documentcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String documentcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.totaltitle
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String totaltitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.imageurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.vrliveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String vrliveurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.pageid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String pageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.startdatecn
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String startdatecn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.venuename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String venuename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.subitemcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String subitemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.awayid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String awayid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.totalguid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String totalguid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.status
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.combatflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String combatflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.lockflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String lockflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.mvlivecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String mvlivecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.homename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String homename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.liveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String liveurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.awayname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String awayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.reserve3
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.venue
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String venue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.awayscore
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String awayscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.reserve2
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.homecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String homecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.reserve1
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.vrtotalcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String vrtotalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.homescore
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String homescore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.livecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String livecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.itemcodename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String itemcodename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.totalurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String totalurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.mvliveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String mvliveurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.awaycode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String awaycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.adcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String adcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.medal
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    private String medal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.homeid
     *
     * @return the value of schedule.homeid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getHomeid() {
        return homeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.homeid
     *
     * @param homeid the value for schedule.homeid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setHomeid(String homeid) {
        this.homeid = homeid == null ? null : homeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.h5pageid
     *
     * @return the value of schedule.h5pageid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getH5pageid() {
        return h5pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.h5pageid
     *
     * @param h5pageid the value for schedule.h5pageid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setH5pageid(String h5pageid) {
        this.h5pageid = h5pageid == null ? null : h5pageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.statusname
     *
     * @return the value of schedule.statusname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getStatusname() {
        return statusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.statusname
     *
     * @param statusname the value for schedule.statusname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setStatusname(String statusname) {
        this.statusname = statusname == null ? null : statusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.itemcode
     *
     * @return the value of schedule.itemcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.itemcode
     *
     * @param itemcode the value for schedule.itemcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.subitemname
     *
     * @return the value of schedule.subitemname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getSubitemname() {
        return subitemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.subitemname
     *
     * @param subitemname the value for schedule.subitemname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setSubitemname(String subitemname) {
        this.subitemname = subitemname == null ? null : subitemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.vrtotalurl
     *
     * @return the value of schedule.vrtotalurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getVrtotalurl() {
        return vrtotalurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.vrtotalurl
     *
     * @param vrtotalurl the value for schedule.vrtotalurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setVrtotalurl(String vrtotalurl) {
        this.vrtotalurl = vrtotalurl == null ? null : vrtotalurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.enddatecn
     *
     * @return the value of schedule.enddatecn
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getEnddatecn() {
        return enddatecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.enddatecn
     *
     * @param enddatecn the value for schedule.enddatecn
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setEnddatecn(String enddatecn) {
        this.enddatecn = enddatecn == null ? null : enddatecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.albumurl
     *
     * @return the value of schedule.albumurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getAlbumurl() {
        return albumurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.albumurl
     *
     * @param albumurl the value for schedule.albumurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setAlbumurl(String albumurl) {
        this.albumurl = albumurl == null ? null : albumurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.title
     *
     * @return the value of schedule.title
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.title
     *
     * @param title the value for schedule.title
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.vrlivecode
     *
     * @return the value of schedule.vrlivecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getVrlivecode() {
        return vrlivecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.vrlivecode
     *
     * @param vrlivecode the value for schedule.vrlivecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setVrlivecode(String vrlivecode) {
        this.vrlivecode = vrlivecode == null ? null : vrlivecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.deletedflag
     *
     * @return the value of schedule.deletedflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.deletedflag
     *
     * @param deletedflag the value for schedule.deletedflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setDeletedflag(String deletedflag) {
        this.deletedflag = deletedflag == null ? null : deletedflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.documentcode
     *
     * @return the value of schedule.documentcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getDocumentcode() {
        return documentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.documentcode
     *
     * @param documentcode the value for schedule.documentcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setDocumentcode(String documentcode) {
        this.documentcode = documentcode == null ? null : documentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.totaltitle
     *
     * @return the value of schedule.totaltitle
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getTotaltitle() {
        return totaltitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.totaltitle
     *
     * @param totaltitle the value for schedule.totaltitle
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setTotaltitle(String totaltitle) {
        this.totaltitle = totaltitle == null ? null : totaltitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.imageurl
     *
     * @return the value of schedule.imageurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.imageurl
     *
     * @param imageurl the value for schedule.imageurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.vrliveurl
     *
     * @return the value of schedule.vrliveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getVrliveurl() {
        return vrliveurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.vrliveurl
     *
     * @param vrliveurl the value for schedule.vrliveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setVrliveurl(String vrliveurl) {
        this.vrliveurl = vrliveurl == null ? null : vrliveurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.pageid
     *
     * @return the value of schedule.pageid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.pageid
     *
     * @param pageid the value for schedule.pageid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setPageid(String pageid) {
        this.pageid = pageid == null ? null : pageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.startdatecn
     *
     * @return the value of schedule.startdatecn
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getStartdatecn() {
        return startdatecn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.startdatecn
     *
     * @param startdatecn the value for schedule.startdatecn
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setStartdatecn(String startdatecn) {
        this.startdatecn = startdatecn == null ? null : startdatecn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.venuename
     *
     * @return the value of schedule.venuename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getVenuename() {
        return venuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.venuename
     *
     * @param venuename the value for schedule.venuename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setVenuename(String venuename) {
        this.venuename = venuename == null ? null : venuename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.subitemcode
     *
     * @return the value of schedule.subitemcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getSubitemcode() {
        return subitemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.subitemcode
     *
     * @param subitemcode the value for schedule.subitemcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setSubitemcode(String subitemcode) {
        this.subitemcode = subitemcode == null ? null : subitemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.awayid
     *
     * @return the value of schedule.awayid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getAwayid() {
        return awayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.awayid
     *
     * @param awayid the value for schedule.awayid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setAwayid(String awayid) {
        this.awayid = awayid == null ? null : awayid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.totalguid
     *
     * @return the value of schedule.totalguid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getTotalguid() {
        return totalguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.totalguid
     *
     * @param totalguid the value for schedule.totalguid
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setTotalguid(String totalguid) {
        this.totalguid = totalguid == null ? null : totalguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.status
     *
     * @return the value of schedule.status
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.status
     *
     * @param status the value for schedule.status
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.combatflag
     *
     * @return the value of schedule.combatflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getCombatflag() {
        return combatflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.combatflag
     *
     * @param combatflag the value for schedule.combatflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setCombatflag(String combatflag) {
        this.combatflag = combatflag == null ? null : combatflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.lockflag
     *
     * @return the value of schedule.lockflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getLockflag() {
        return lockflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.lockflag
     *
     * @param lockflag the value for schedule.lockflag
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setLockflag(String lockflag) {
        this.lockflag = lockflag == null ? null : lockflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.mvlivecode
     *
     * @return the value of schedule.mvlivecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getMvlivecode() {
        return mvlivecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.mvlivecode
     *
     * @param mvlivecode the value for schedule.mvlivecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setMvlivecode(String mvlivecode) {
        this.mvlivecode = mvlivecode == null ? null : mvlivecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.homename
     *
     * @return the value of schedule.homename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getHomename() {
        return homename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.homename
     *
     * @param homename the value for schedule.homename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setHomename(String homename) {
        this.homename = homename == null ? null : homename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.liveurl
     *
     * @return the value of schedule.liveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getLiveurl() {
        return liveurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.liveurl
     *
     * @param liveurl the value for schedule.liveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setLiveurl(String liveurl) {
        this.liveurl = liveurl == null ? null : liveurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.awayname
     *
     * @return the value of schedule.awayname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getAwayname() {
        return awayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.awayname
     *
     * @param awayname the value for schedule.awayname
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setAwayname(String awayname) {
        this.awayname = awayname == null ? null : awayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.reserve3
     *
     * @return the value of schedule.reserve3
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.reserve3
     *
     * @param reserve3 the value for schedule.reserve3
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.venue
     *
     * @return the value of schedule.venue
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getVenue() {
        return venue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.venue
     *
     * @param venue the value for schedule.venue
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setVenue(String venue) {
        this.venue = venue == null ? null : venue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.awayscore
     *
     * @return the value of schedule.awayscore
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getAwayscore() {
        return awayscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.awayscore
     *
     * @param awayscore the value for schedule.awayscore
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setAwayscore(String awayscore) {
        this.awayscore = awayscore == null ? null : awayscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.reserve2
     *
     * @return the value of schedule.reserve2
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.reserve2
     *
     * @param reserve2 the value for schedule.reserve2
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.homecode
     *
     * @return the value of schedule.homecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getHomecode() {
        return homecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.homecode
     *
     * @param homecode the value for schedule.homecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setHomecode(String homecode) {
        this.homecode = homecode == null ? null : homecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.reserve1
     *
     * @return the value of schedule.reserve1
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.reserve1
     *
     * @param reserve1 the value for schedule.reserve1
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.vrtotalcode
     *
     * @return the value of schedule.vrtotalcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getVrtotalcode() {
        return vrtotalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.vrtotalcode
     *
     * @param vrtotalcode the value for schedule.vrtotalcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setVrtotalcode(String vrtotalcode) {
        this.vrtotalcode = vrtotalcode == null ? null : vrtotalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.homescore
     *
     * @return the value of schedule.homescore
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getHomescore() {
        return homescore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.homescore
     *
     * @param homescore the value for schedule.homescore
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setHomescore(String homescore) {
        this.homescore = homescore == null ? null : homescore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.livecode
     *
     * @return the value of schedule.livecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getLivecode() {
        return livecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.livecode
     *
     * @param livecode the value for schedule.livecode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setLivecode(String livecode) {
        this.livecode = livecode == null ? null : livecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.itemcodename
     *
     * @return the value of schedule.itemcodename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getItemcodename() {
        return itemcodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.itemcodename
     *
     * @param itemcodename the value for schedule.itemcodename
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setItemcodename(String itemcodename) {
        this.itemcodename = itemcodename == null ? null : itemcodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.totalurl
     *
     * @return the value of schedule.totalurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getTotalurl() {
        return totalurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.totalurl
     *
     * @param totalurl the value for schedule.totalurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setTotalurl(String totalurl) {
        this.totalurl = totalurl == null ? null : totalurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.mvliveurl
     *
     * @return the value of schedule.mvliveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getMvliveurl() {
        return mvliveurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.mvliveurl
     *
     * @param mvliveurl the value for schedule.mvliveurl
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setMvliveurl(String mvliveurl) {
        this.mvliveurl = mvliveurl == null ? null : mvliveurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.awaycode
     *
     * @return the value of schedule.awaycode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getAwaycode() {
        return awaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.awaycode
     *
     * @param awaycode the value for schedule.awaycode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setAwaycode(String awaycode) {
        this.awaycode = awaycode == null ? null : awaycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.adcode
     *
     * @return the value of schedule.adcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getAdcode() {
        return adcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.adcode
     *
     * @param adcode the value for schedule.adcode
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode == null ? null : adcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.medal
     *
     * @return the value of schedule.medal
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public String getMedal() {
        return medal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.medal
     *
     * @param medal the value for schedule.medal
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    public void setMedal(String medal) {
        this.medal = medal == null ? null : medal.trim();
    }
}