package com.example.back.common;

public class Total {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.bronze
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String bronze;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.rank
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.count
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.silver
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String silver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.countryname
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String countryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.gold
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String gold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column total.countryid
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    private String countryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.bronze
     *
     * @return the value of total.bronze
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getBronze() {
        return bronze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.bronze
     *
     * @param bronze the value for total.bronze
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setBronze(String bronze) {
        this.bronze = bronze == null ? null : bronze.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.rank
     *
     * @return the value of total.rank
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.rank
     *
     * @param rank the value for total.rank
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.count
     *
     * @return the value of total.count
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.count
     *
     * @param count the value for total.count
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.silver
     *
     * @return the value of total.silver
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getSilver() {
        return silver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.silver
     *
     * @param silver the value for total.silver
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setSilver(String silver) {
        this.silver = silver == null ? null : silver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.countryname
     *
     * @return the value of total.countryname
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getCountryname() {
        return countryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.countryname
     *
     * @param countryname the value for total.countryname
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setCountryname(String countryname) {
        this.countryname = countryname == null ? null : countryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.gold
     *
     * @return the value of total.gold
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.gold
     *
     * @param gold the value for total.gold
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setGold(String gold) {
        this.gold = gold == null ? null : gold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column total.countryid
     *
     * @return the value of total.countryid
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public String getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column total.countryid
     *
     * @param countryid the value for total.countryid
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    public void setCountryid(String countryid) {
        this.countryid = countryid == null ? null : countryid.trim();
    }
}