package com.example.back.dao;

import com.example.back.common.schedule;
import com.example.back.common.scheduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface scheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    long countByExample(scheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int deleteByExample(scheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int insert(schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int insertSelective(schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    List<schedule> selectByExample(scheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int updateByExampleSelective(@Param("record") schedule record, @Param("example") scheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int updateByExample(@Param("record") schedule record, @Param("example") scheduleExample example);

    List<schedule> selectByAny(String date,String item,String place);
}