package com.example.back.dao;

import com.example.back.common.total;

public interface totalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    int insert(total record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 00:10:38 CST 2022
     */
    int insertSelective(total record);
}