package com.example.back.dao;

import com.example.back.common.Schedule;
import com.example.back.common.Total;
import com.example.back.common.TotalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    long countByExample(TotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    int deleteByExample(TotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    int insert(Total record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    int insertSelective(Total record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    List<Total> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    List<Total> selectByExample(TotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    int updateByExampleSelective(@Param("record") Total record, @Param("example") TotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 10:58:16 CST 2022
     */
    int updateByExample(@Param("record") Total record, @Param("example") TotalExample example);
}