package com.example.back.dao;

import com.example.back.common.total;
import com.example.back.common.totalExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface totalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    long countByExample(totalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int deleteByExample(totalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int insert(total record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int insertSelective(total record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    List<total> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    List<total> selectByExample(totalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int updateByExampleSelective(@Param("record") total record, @Param("example") totalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table total
     *
     * @mbg.generated Thu Mar 24 16:19:06 CST 2022
     */
    int updateByExample(@Param("record") total record, @Param("example") totalExample example);
}